name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Verify Swift Version
      run: swift --version

    - name: Check Syntax
      run: |
        cd VoiceBudget
        swiftc -parse App/VoiceBudgetApp.swift

    - name: Build Project
      run: |
        xcodebuild -scheme VoiceBudget \
                   -destination 'platform=iOS Simulator,name=iPhone 15' \
                   -configuration Debug \
                   build \
                   CODE_SIGNING_ALLOWED=NO

    - name: Run Tests (if available)
      run: |
        xcodebuild -scheme VoiceBudget \
                   -destination 'platform=iOS Simulator,name=iPhone 15' \
                   -configuration Debug \
                   test \
                   CODE_SIGNING_ALLOWED=NO || echo "No tests configured"

    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          **/*.app
          **/*.dSYM
        retention-days: 30